### PR TITLE
Include storage module

### PR DESCRIPTION
**Pull request by euank**
Previously it was excluded from 'lib', and so was not even compiled.

Errors that prevented it from compiling were also fixed.

### CODE REVIEW

**Comment by dariusc93** [comment]
Thanks for the PR. In a different repo, I have included it, but I thought I have included in this one too. I believe it was excluded due to some errors initially but I will merge this soon!

**Comment by euank** [comment]
@dariusc93 is there a better repo to be using than this one? Is that the "different repo"?

Or is this a mirror of some internal repo?

**Comment by dariusc93** [comment]
@euank I do have the same repo internally that is slightly more up to date than this one, however we are doing some changes so a push to github probably wont be until some of the changes are finished (we are rewriting since we moved to using rpc with libvirt). I will merge this PR soon though and update the crate (dont know when I will be able to update it but you can use git to obtain the project from the repo).

**Comment by euank** [comment]
I made further changes here since I realized there wasn't really a way to define a pool nor various other niceties.

I also added an integ test. I don't know how you feel about travis CI, but I also included a .travis.yml for it (passing [here](https://travis-ci.org/euank/libvirt-rs/builds/186743560)). Happy to remove it if you'd prefer not to use that service.

----------------

I'm interested in the RPC version. Due to the comment [here](https://github.com/libvirt/libvirt/blob/866641d4c5706413393913fdb3bb1cd077683d21/src/remote/remote_protocol.x#L27-L29) in their rpc spec, I doubted whether it was a good idea when I was trying to write it.

Are you planning to just target specific versions of libvirt? To ignore the warning and trust that in reality it's fairly stable? Something else?

My thoughts were that changing the glibc `rpcgen` program to generate rust instead of C, and generating the needed structs/etc from the `.x` file upstream would be a sane path forwards, but I haven't gotten around to actually making those changes and it looks *really hard*!

Are you using, or planning to use, code generation off the `.x` file?

**Comment by euank** [comment]
ping @dariusc93; if you want me to scope this back down to just the first 3 commits I'd be happy to.

**Pull request merged**
